image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore ./GST.Library.sln
build_script:
- powershell .\build.ps1
before_build:
- appveyor-retry dotnet restore -v Minimal
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Nuget
deploy:
  - provider: NuGet
    api_key:
      secure: QsjsTYGlMBE2oXS8QLMq3TvzcKhW/xatLFuSg+vfoJeaLYxJ1mpfMWs+8chehZbo
    artifact: /GST\.Library.*\.nupkg/
test_script:
- dotnet test -c Test ./test/GST.Library.API.REST.Tests/GST.Library.API.REST.Tests.csproj
- dotnet test -c Test ./test/GST.Library.Data.Tests/GST.Library.Data.Tests.csproj
- dotnet test -c Test ./test/GST.Library.Helper.Tests/GST.Library.Helper.Tests.csproj
- dotnet test -c Test ./test/GST.Library.StoredProcedureHelper.Tests/GST.Library.StoredProcedureHelper.Tests.csproj


