image: Visual Studio 2015
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore ./src/GST.Library.API.REST/project.json
  - dotnet restore ./src/GST.Library.Data/project.json
  - dotnet restore ./src/GST.Library.Helper/project.json
  - dotnet restore ./src/GST.Library.StoredProcedureHelper/project.json
  - dotnet restore ./test/GST.Library.API.REST.Tests/project.json
  - dotnet restore ./test/GST.Library.Data.Tests/project.json
  - dotnet restore ./test/GST.Library.Helper.Tests/project.json
  - dotnet restore ./test/GST.Library.StoredProcedureHelper.Tests/project.json
build_script:
- powershell .\build.ps1 -t BuildPackages
before_build:
- appveyor-retry dotnet restore -v Minimal
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Nuget
deploy:
  - provider: NuGet.org
test_script:
- dotnet test -f netcoreapp1.1 -c Test ./test/GST.Library.API.REST.Tests/project.json
- dotnet test -f netcoreapp1.1 -c Test ./test/GST.Library.Data.Tests/project.json
- dotnet test -f netcoreapp1.1 -c Test ./test/GST.Library.Helper.Tests/project.json
- dotnet test -f netcoreapp1.1 -c Test ./test/GST.Library.StoredProcedureHelper.Tests/project.json